#!/usr/bin/env python

import re
import sys

commitMessageFile = open(sys.argv[1],'r')
commitMessage = commitMessageFile.readline()


example = "йцукенгшщзхъфывапролджэячсмитьбюЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ"
for i in range(len(commitMessage)):
	for j in range(len(example)):
		if commitMessage[i] == example[j]:
			print("Commit message is contain russian symbols")
			sys.exit(1)

			
if len(commitMessage) < 10:
    print("Commit message is less than the required 10 characters.")
    sys.exit(1)
	
if len(commitMessage.split(' ')) < 2:
    print("Commit message is less than 2 words.")
    sys.exit(1)

print("Commit message is validated")
sys.exit(0)